version: 1
disable_existing_loggers: False
formatters:
  rich_formatter:
    class: rich.logging.RichHandler
    format: "{time} - {message}"
handlers:
  console_handler:
    class: logging.StreamHandler
    level: INFO
    formatter: rich_formatter
    stream: ext://sys.stdout
  file_handler:
    class: logging.FileHandler
    level: INFO
    formatter: rich_formatter
    filename: mylog.log
root:
  level: INFO
  handlers: [console_handler, file_handler]
